export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";
export const PRODUCT_LIST_RESET = "PRODUCT_LIST_RESET";

export const PRODUCT_GET_REQUEST = "PRODUCT_GET_REQUEST";
export const PRODUCT_GET_SUCCESS = "PRODUCT_GET_SUCCESS";
export const PRODUCT_GET_FAIL = "PRODUCT_GET_FAIL";

export const PRODUCT_GET_BYFILTER_REQUEST = "PRODUCT_GET_BYFILTER_REQUEST";
export const PRODUCT_GET_BYFILTER_SUCCESS = "PRODUCT_GET_BYFILTER_SUCCESS";
export const PRODUCT_GET_BYFILTER_FAIL = "PRODUCT_GET_BYFILTER_FAIL";
export const PRODUCT_GET_BYFILTER_RESET = "PRODUCT_GET_BYFILTER_RESET";
export const GET_PRODUCT_SUBCATEGORY_REQUEST =
  "GET_PRODUCT_SUBCATEGORY_REQUEST";
export const GET_PRODUCT_SUBCATEGORY_SUCCESS =
  "GET_PRODUCT_SUBCATEGORY_SUCCESS";
export const GET_PRODUCT_SUBCATEGORY_FAIL = "GET_PRODUCT_SUBCATEGORY_FAIL";

export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL";
export const CREATE_PRODUCT_RESET = "CREATE_PRODUCT_RESET";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";
